services:

  postgres:
    image: postgres:${SW_VERSION_TAG_POSTGRES}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - dev_network

  pgadmin4:
    image: elestio/pgadmin:${SW_VERSION_TAG_PGADMIN}
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - '8080:8080'
    networks:
      - dev_network
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro

networks:
  dev_network:
    driver: bridge

volumes:
  postgres_data:
